server:
  port: 9099

spring:
  datasource:
    url: jdbc:h2:mem:golfersDB
    username: root
    password: toor
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

