DROP TABLE IF EXISTS GOLFERS;

CREATE TABLE GOLFERS (
id INTEGER NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
nationality VARCHAR(30) NOT NULL,
age INTEGER NOT NULL,
handicap INTEGER
);



DROP TABLE IF EXISTS COURSES;

CREATE TABLE COURSES(
id INTEGER NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
latitude FLOAT NOT NULL,
longitude FLOAT NOT NULL,
rating FLOAT,
yardage INTEGER NOT NULL,
par INTEGER NOT NULL
);
